name: gstplayer_example
description: "Demonstrates how to use the gstplayer plugin."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  gstplayer:
    path: ../
  cupertino_icons: ^1.0.9
  chat_context_menu: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  config:
    enable-swift-package-manager: true
  uses-material-design: true

  assets:
    - assets/sample.mp4
    - assets/sample.srt
