import 'package:flutter/material.dart';
import 'package:theme_extensions_builder_annotation/theme_extensions_builder_annotation.dart';

part 'video_controls_theme.g.theme.dart';

/// 内置视频控件栏视觉样式 / Visual styling for the built-in video control bar.
///
/// 在 `ThemeData.extensions` 中注册以自定义；未注册时 [VideoControls] 回退至
/// [VideoControlsTheme.material] / [VideoControlsTheme.cupertino] 预设。
/// Register in `ThemeData.extensions` to customize; [VideoControls] falls back to
/// [VideoControlsTheme.material] / [VideoControlsTheme.cupertino] presets when absent.
///
/// `copyWith`、`lerp`、`==`、`hashCode` 由 `theme_extensions_builder` 生成（见 `video_controls_theme.g.theme.dart`）。
/// `copyWith`, `lerp`, `==`, and `hashCode` are generated by `theme_extensions_builder`.
@ThemeExtensions()
class VideoControlsTheme extends ThemeExtension<VideoControlsTheme>
    with _$VideoControlsTheme {
  const VideoControlsTheme({
    required this.iconColor,
    required this.activeIconColor,
    required this.activeTrackColor,
    required this.inactiveTrackColor,
    required this.bufferedTrackColor,
    required this.thumbColor,
    required this.textColor,
    required this.backgroundColor,
    required this.primaryIconSize,
    required this.secondaryIconSize,
    required this.centerButtonSize,
    required this.barPadding,
    required this.borderRadius,
    required this.bufferingScrimColor,
    required this.bufferingIndicatorColor,
    required this.bufferingTextColor,
    required this.fitScreenIcon,
    required this.fillScreenIcon,
    required this.stretchScreenIcon,
    this.bufferingTextStyle,
  });

  /// Material 预设（实心图标、宽滑条、半透明 scrim）/ Material preset.
  factory VideoControlsTheme.material() => const VideoControlsTheme(
    iconColor: Color(0xFFFFFFFF),
    activeIconColor: Color(0xFF82B1FF),
    activeTrackColor: Color(0xFFFFFFFF),
    inactiveTrackColor: Color.fromARGB(118, 255, 255, 255),
    bufferedTrackColor: Color.fromARGB(149, 255, 255, 255),
    thumbColor: Color(0xFFFFFFFF),
    textColor: Color(0xFFFFFFFF),
    backgroundColor: Color(0x99000000),
    primaryIconSize: 24,
    secondaryIconSize: 20,
    centerButtonSize: 48,
    barPadding: EdgeInsets.symmetric(horizontal: 10, vertical: 4),
    borderRadius: 0,
    bufferingScrimColor: Colors.transparent,
    bufferingIndicatorColor: Color(0xFFFFFFFF),
    bufferingTextColor: Color(0xFFFFFFFF),
    fitScreenIcon: Icons.fit_screen,
    fillScreenIcon: Icons.crop_free,
    stretchScreenIcon: Icons.aspect_ratio,
  );

  /// Cupertino 预设（细轨道、圆角半透明栏）/ Cupertino preset.
  factory VideoControlsTheme.cupertino() => const VideoControlsTheme(
    iconColor: Color(0xFFFFFFFF),
    activeIconColor: Color(0xFFFFFFFF),
    activeTrackColor: Color(0xFFFFFFFF),
    inactiveTrackColor: Color(0x3DFFFFFF),
    bufferedTrackColor: Color(0x66FFFFFF),
    thumbColor: Color(0xFFFFFFFF),
    textColor: Color(0xFFEBEBF5),
    backgroundColor: Color(0x66000000),
    primaryIconSize: 24,
    secondaryIconSize: 20,
    centerButtonSize: 48,
    barPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 0),
    borderRadius: 14,
    bufferingScrimColor: Colors.transparent,
    bufferingIndicatorColor: Color(0xFFEBEBF5),
    bufferingTextColor: Color(0xFFEBEBF5),
    fitScreenIcon: Icons.fit_screen,
    fillScreenIcon: Icons.crop_free,
    stretchScreenIcon: Icons.aspect_ratio,
  );

  /// 空闲控件图标颜色 / Color of idle control icons.
  final Color iconColor;

  /// 激活态高亮（如循环已开）/ Color for active toggles (e.g. looping on).
  final Color activeIconColor;

  /// 已播放进度条段 / Played portion of the seek bar.
  final Color activeTrackColor;

  /// 未播放进度条段 / Unplayed portion of the seek bar.
  final Color inactiveTrackColor;

  /// 已缓冲 ahead 段 / Buffered-ahead portion of the seek bar.
  final Color bufferedTrackColor;

  /// 滑块颜色 / Seek bar thumb color.
  final Color thumbColor;

  /// 时间标签颜色 / Position/duration label color.
  final Color textColor;

  /// 控件栏 / scrim 背景色 / Control bar / scrim background color.
  final Color backgroundColor;

  /// 中央播放/暂停图标尺寸 / Central play/pause icon size.
  final double primaryIconSize;

  /// 次要图标尺寸（静音、循环、倍速）/ Secondary icon size.
  final double secondaryIconSize;

  /// 中央播放/暂停按钮容器尺寸 / Central play/pause button container size.
  final double centerButtonSize;

  /// 底栏内边距 / Bottom bar padding.
  final EdgeInsets barPadding;

  /// 底栏圆角 / Control bar corner radius.
  final double borderRadius;

  /// 缓冲遮罩色；默认透明（非全屏遮挡）/ Buffering scrim; default transparent.
  final Color bufferingScrimColor;

  /// 缓冲指示器颜色 / Buffering spinner color.
  final Color bufferingIndicatorColor;

  /// 缓冲进度文字颜色 / Buffering percent label color.
  final Color bufferingTextColor;

  /// 缓冲进度文字样式；为 null 时用 [bufferingTextColor] + 默认字号 / Optional buffering label style.
  final TextStyle? bufferingTextStyle;

  /// 铺满模式适应图标 / Icon for fit mode.
  final IconData fitScreenIcon;

  /// 铺满模式铺满图标 / Icon for fill mode.
  final IconData fillScreenIcon;

  /// 铺满模式拉伸图标 / Icon for stretch mode.
  final IconData stretchScreenIcon;
}
