LOCAL_PATH := $(call my-dir)

# A throwaway module that pulls in libgstreamer_android.so (which is what we
# actually want to ship). We have no JNI C of our own; the CMake libgstplayer.so
# links against libgstreamer_android.so at build time; the umbrella .so is built
# at compile time and packaged via android/build/gstreamer/jniLibs/.
include $(CLEAR_VARS)
LOCAL_MODULE    := dummy
LOCAL_SRC_FILES := dummy.c
LOCAL_SHARED_LIBRARIES := gstreamer_android
include $(BUILD_SHARED_LIBRARY)

ifndef GSTREAMER_ROOT_ANDROID
$(error GSTREAMER_ROOT_ANDROID is not defined!)
endif

ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
GSTREAMER_ROOT := $(GSTREAMER_ROOT_ANDROID)/armv7
else ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
GSTREAMER_ROOT := $(GSTREAMER_ROOT_ANDROID)/arm64
else ifeq ($(TARGET_ARCH_ABI),x86)
GSTREAMER_ROOT := $(GSTREAMER_ROOT_ANDROID)/x86
else ifeq ($(TARGET_ARCH_ABI),x86_64)
GSTREAMER_ROOT := $(GSTREAMER_ROOT_ANDROID)/x86_64
else
$(error Target arch ABI not supported: $(TARGET_ARCH_ABI))
endif

GSTREAMER_NDK_BUILD_PATH := $(GSTREAMER_ROOT)/share/gst-android/ndk-build/

# Hand-written plugin set aligned with GStreamer 1.28.6 plugins.mk category
# *names*, matching iOS ios_plugins.c + macOS gstreamer_playback_plugins.txt
# for the sample formats. Do NOT assign $(GSTREAMER_PLUGINS_CORE) / CODECS /
# NET / SYS wholesale: 1.28.6 groups pull Rust plugins (lcevcdecoder,
# threadshare, rs*) whose .la deps ndk-build whole-archive cannot resolve.
#
# Format map:
#   mp4/mov  isomp4 + androidmedia (H.264/AAC) / libav (MPEG-4 ASP, …)
#   mkv/webm matroska + androidmedia / vpx / opus / vorbis / libav
#   avi      avi (avidemux) + libav / jpeg / mpg123
#   ogg/ogv  ogg + theora / vorbis
#   flv/asf/ts/ps  dedicated demuxers; libav fills remaining codecs
#
# HTTP: souphttpsrc (official C plugin from the 1.28.6 Android SDK; same as
# iOS/macOS). No gst-plugins-rs reqwest / Rust cross-compile on Android.
#
# `opengl` is REQUIRED for hardware decode: Qualcomm/Android MediaCodec
# (amcvideodec) only emits GL textures (memory:GLMemory, texture-target=
# external-oes). Without it: "Codec only supports GL output but downstream
# does not" -> not-negotiated.
#
# gst_init() calls gst_init_static_plugins() generated by gstreamer-1.0.mk
# from this list (GST_PLUGIN_STATIC_REGISTER per plugin). dummy.c does not
# register plugins.
GSTREAMER_PLUGINS := \
    coreelements app typefindfunctions playback pbtypes gio autodetect \
    audioconvert audioresample audiorate audiofx volume \
    videoconvertscale videofilter videorate videocrop deinterlace \
    isomp4 matroska avi ogg flv id3demux subparse audioparsers videoparsersbad \
    jpeg png theora vpx opus vorbis androidmedia \
    libav mpegpsdemux mpegtsdemux asf mpg123 wavparse \
    opengl opensles \
    soup tcp udp

GSTREAMER_EXTRA_DEPS := gstreamer-video-1.0 gstreamer-app-1.0
# TLS for https://. 1.28.6 Android SDK ships openssl (docs still mention gnutls).
G_IO_MODULES := openssl
# -lssl/-lcrypto for the openssl TLS backend; -lEGL/-lGLESv2 for the opengl
# plugin (glcolorconvert receives amcvideodec GL textures).
GSTREAMER_EXTRA_LIBS := -lssl -lcrypto -lEGL -lGLESv2

include $(GSTREAMER_NDK_BUILD_PATH)/gstreamer-1.0.mk
